version: "3.8"

# CouchDB with Traefik reverse proxy configuration
# Accessible via: ${COUCHDB_DOMAIN} (configurable in .env)

services:
  couchdb:
    image: couchdb:latest
    container_name: ${CONTAINER_NAME_PREFIX}-app
    restart: unless-stopped
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
      - TZ=${TZ}
    volumes:
      - couchdb_data:/opt/couchdb/data
    networks:
      - app-network
      - traefik_public
    labels:
      # Domain for CouchDB access - ${COUCHDB_DOMAIN}
      - "traefik.enable=true"
      - "traefik.http.routers.couchdb.rule=Host(`${COUCHDB_DOMAIN}`)"
      - "traefik.http.routers.couchdb.entrypoints=websecure"
      - "traefik.http.routers.couchdb.tls.certresolver=letsencrypt"
      - "traefik.http.services.couchdb.loadbalancer.server.port=5984"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${CONTAINER_NAME_PREFIX}-cloudflared
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    # This command checks if the token is set before running the tunnel
    # Note: Cloudflare Tunnel may not be needed if Traefik is handling external access
    command: sh -c 'if [ -n "$TUNNEL_TOKEN" ]; then cloudflared tunnel --no-autoupdate run --token $TUNNEL_TOKEN; else echo "CLOUDFLARE_TUNNEL_TOKEN is not set. Service is idle." && tail -f /dev/null; fi'
    networks:
      - app-network
      - traefik_public

volumes:
  couchdb_data:
    name: ${CONTAINER_NAME_PREFIX}-data

networks:
  app-network:
    name: ${CONTAINER_NAME_PREFIX}-app
  traefik_public:
    external: true